# Generated by Django 3.1.3 on 2020-11-19 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='New Album')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSVEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('imageRef', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=2000)),
                ('licenseType', models.CharField(max_length=5)),
                ('userName', models.CharField(max_length=200)),
                ('superTags', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=200)),
                ('dateTaken', models.DateField(blank=True, null=True)),
                ('numberOfPeople', models.PositiveIntegerField(default=0)),
                ('modelRelease', models.CharField(max_length=20)),
                ('isThereProperty', models.CharField(max_length=1)),
                ('propertyRelease', models.CharField(max_length=20)),
                ('primaryCategory', models.CharField(max_length=20)),
                ('secondaryCategory', models.CharField(max_length=20)),
                ('imageType', models.CharField(max_length=20)),
                ('exclusiveToAlamy', models.CharField(max_length=1)),
                ('additionalInfo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('remote_key', models.CharField(default='fjWM4F', max_length=20)),
                ('remote_id', models.PositiveIntegerField(default=157544933)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='.default.jpg', max_length=200)),
                ('title', models.TextField(null=True)),
                ('sortkey', models.PositiveIntegerField(null=True, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('taken_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('primaryCategory', models.CharField(max_length=20, null=True)),
                ('secondaryCategory', models.CharField(max_length=20, null=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('keywords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homePIX.keywords')),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homePIX.directory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homePIX.picturefile'),
        ),
        migrations.CreateModel(
            name='CSVContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.csventry')),
                ('picturefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.picturefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homePIX.picturefile')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.album')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.picturefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homePIX.picturefile'),
        ),
    ]
