# Generated by Django 2.1 on 2020-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='remote_key',
            field=models.CharField(default='fjWM4F', max_length=20),
        ),
        migrations.AlterField(
            model_name='directory',
            name='count',
            field=models.PositiveIntegerField(default=157544933),
        ),
    ]
