# Generated by Django 3.1.3 on 2020-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturefile',
            name='hits',
        ),
        migrations.AddField(
            model_name='directory',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
