# Generated by Django 3.1.3 on 2020-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0002_auto_20201119_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picturefile',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
