# Generated by Django 2.1 on 2020-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0002_auto_20200525_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='remote_id',
            field=models.PositiveIntegerField(default=157544933),
        ),
        migrations.AlterField(
            model_name='directory',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
