# Generated by Django 2.1 on 2020-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0003_auto_20200525_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('imageRef', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=2000)),
                ('licenseType', models.CharField(max_length=5)),
                ('userName', models.CharField(max_length=200)),
                ('superTags', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=200)),
                ('dateTaken', models.DateTimeField(null=True)),
                ('numberOfPeople', models.PositiveIntegerField(default=0)),
                ('modelRelease', models.CharField(max_length=20)),
                ('isThereProperty', models.CharField(max_length=1)),
                ('propertyRelease', models.CharField(max_length=20)),
                ('primaryCategory', models.CharField(max_length=20)),
                ('secondaryCategory', models.CharField(max_length=20)),
                ('imageType', models.CharField(max_length=20)),
                ('exclusiveToAlamy', models.CharField(max_length=1)),
                ('additionalInfo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
