# Generated by Django 2.1 on 2020-05-29 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0004_csventry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csventry',
            name='dateTaken',
            field=models.DateTimeField(default=datetime.datetime(1966, 1, 28, 0, 0)),
        ),
    ]
