# Generated by Django 2.1 on 2020-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0005_auto_20200529_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csventry',
            name='dateTaken',
            field=models.DateTimeField(default='1966-01-01 06:00:00.000000-08:00'),
        ),
    ]
