# Generated by Django 2.1 on 2020-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0006_auto_20200529_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csventry',
            name='dateTaken',
            field=models.DateTimeField(),
        ),
    ]
