# Generated by Django 2.1 on 2020-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0007_auto_20200529_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csventry',
            name='dateTaken',
            field=models.DateField(),
        ),
    ]
