# Generated by Django 2.1 on 2020-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0008_auto_20200529_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csventry',
            name='dateTaken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
