# Generated by Django 2.1 on 2020-05-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0009_auto_20200529_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.CSVEntry')),
                ('picturefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePIX.PictureFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
