# Generated by Django 2.1 on 2020-05-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0010_csvcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturefile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picturefile',
            name='primaryCategory',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='picturefile',
            name='secondaryCategory',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
