# Generated by Django 2.1 on 2020-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0011_auto_20200531_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
