# Generated by Django 2.1 on 2020-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0012_auto_20200531_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='taken_on',
            field=models.DateTimeField(auto_now_add=True, default='1966-01-28'),
            preserve_default=False,
        ),
    ]
