# Generated by Django 2.1 on 2020-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePIX', '0013_auto_20200610_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='taken_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
