# Generated by Django 2.2.6 on 2019-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191124_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='sortkey',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
