# Generated by Django 2.2.6 on 2019-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191124_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picturefile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='picturefile',
            name='taken_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
