# Generated by Django 2.2.6 on 2019-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191125_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='picturefile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='picturefile',
            name='taken_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
