# Generated by Django 2.2.6 on 2020-05-23 08:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191204_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='sortkey',
            field=models.PositiveIntegerField(default=builtins.id, unique=True),
        ),
    ]
