# Generated by Django 2.2.6 on 2020-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200523_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefile',
            name='sortkey',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
